services:
  dev-cw-connector:
    build: .
    container_name: dev-cw-connector
    volumes:
      - ./:/app
      - ./docker/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - "8000:8000"
    environment:
      - XDEBUG_MODE=debug
      - XDEBUG_SESSION=1
      - COMPOSER_HOME=/composer
    command: ["/bin/sh", "-c", "composer install --no-progress --no-interaction && php -S 0.0.0.0:8000 -t public"]
    networks:
      - cw-network

networks:
  cw-network:
    external: true
